<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HealthRecordController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\BreedingRecordController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\MilkSupplyController;
use App\Http\Controllers\SupplierPaymentController;
use App\Http\Controllers\AnimalController;
use App\Http\Controllers\MilkProductionController;  
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/offline', 'offline');


// Public routes
Route::get('/', function () {
    return redirect()->route('login');
});

// Authentication routes (generated by laravel/ui)
Auth::routes();

// Protected routes (require authentication)
Route::middleware(['auth'])->group(function () {
    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    
    // Animal Management
    Route::resource('animals', AnimalController::class);
    Route::get('animals/search', [AnimalController::class, 'search'])->name('animals.search');
    
    // Profile
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    
    // Breeding Records (nested under animals)
    Route::prefix('animals/{animal}')->group(function () {
        Route::resource('breeding', 'BreedingRecordController')->except(['show']);
    });
    
    // Milk Production (nested under animals)
    Route::prefix('animals/{animal}')->group(function () {
        Route::resource('milk', 'MilkProductionController')->except(['show']);
    });
    
    // Health Records (nested under animals)
    Route::prefix('animals/{animal}')->group(function () {
        Route::resource('health', 'HealthRecordController')->except(['show']);
    });



// Add these routes

// Suppliers Management

   
    Route::post('/milk-supplies/{milkSupply}/approve', [MilkSupplyController::class, 'approve'])
        ->name('milk-supplies.approve');
    Route::get('/milk-supplies/daily-report', [MilkSupplyController::class, 'dailyReport'])
        ->name('milk-supplies.daily-report');
    
    // Supplier Payments
   
    Route::post('/payments/{payment}/approve', [SupplierPaymentController::class, 'approve'])
        ->name('payments.approve');
    Route::post('/payments/{payment}/reject', [SupplierPaymentController::class, 'reject'])
        ->name('payments.reject');
    Route::post('/payments/bulk-approve', [SupplierPaymentController::class, 'bulkApprove'])
        ->name('payments.bulk-approve');
    Route::post('/payments/generate', [SupplierPaymentController::class, 'generatePayments'])
        ->name('payments.generate');

        Route::resource('suppliers', SupplierController::class);
    
        // Milk Supplies
        Route::resource('milk-supplies', MilkSupplyController::class);

        Route::resource('payments', SupplierPaymentController::class);

    
    Route::prefix('reports')->group(function () {
        Route::get('/', [ReportController::class, 'index'])->name('reports.index');
        Route::post('/generate', [ReportController::class, 'generate'])->name('reports.generate');
    });
    // Admin only routes
    Route::middleware(['can:manage-users'])->group(function () {
        Route::resource('users', 'UserController')->except(['show']);
    });
    Route::get('milk-production/monthly-report', [MilkProductionController::class, 'monthlyReport'])->name('milk-production.monthly-report');

    Route::get('health-records/active', [HealthRecordController::class, 'activeIssues'])->name('health-records.active');
    Route::get('health-records/monthly-report', [HealthRecordController::class, 'monthlyReport'])->name('health-records.monthly-report');
    
    // Milk Production Routes
    Route::get('milk-production/quick-entry', [MilkProductionController::class, 'quickEntry'])->name('milk-production.quick-entry');
Route::resource('milk-production', MilkProductionController::class);
Route::get('/milk-production/create', [MilkProductionController::class, 'create'])->name('milk-production.create');

Route::post('milk-production/quick-entry', [MilkProductionController::class, 'storeMultiple'])->name('milk-production.store-multiple');
Route::get('milk-production/monthly-report', [MilkProductionController::class, 'monthlyReport'])->name('milk-production.monthly-report');

Route::get('breeding-records/pregnant', [BreedingRecordController::class, 'pregnantAnimals'])->name('breeding-records.pregnant');
Route::get('breeding-records/due-for-calving', [BreedingRecordController::class, 'dueForCalving'])->name('breeding-records.due-for-calving');
Route::get('breeding-records/calendar', [BreedingRecordController::class, 'breedingCalendar'])->name('breeding-records.calendar');
Route::get('breeding-records/performance-report', [BreedingRecordController::class, 'performanceReport'])->name('breeding-records.performance-report');
// Additional health record routes



// Milk Approval Routes
Route::get('users/pending-milk-approvals', [UserController::class, 'pendingMilkApprovals'])
     ->name('users.pending-milk-approvals');
Route::post('users/approve-milk-record/{id}', [UserController::class, 'approveMilkRecord'])
     ->name('users.approve-milk-record');
Route::post('users/reject-milk-record/{id}', [UserController::class, 'rejectMilkRecord'])
     ->name('users.reject-milk-record');

     Route::resource('users', UserController::class);
// User Activity Log
Route::get('users/{user}/activity-log', [UserController::class, 'activityLog'])
     ->name('users.activity-log');
// Health Records Routes
Route::resource('health-records', HealthRecordController::class);


Route::resource('breeding-records', BreedingRecordController::class);

// Additional breeding record routes

});

Route::post('/expenses/{expense}/approve', [ExpenseController::class, 'approve'])
    ->name('expenses.approve');
Route::post('/expenses/{expense}/reject', [ExpenseController::class, 'reject'])
    ->name('expenses.reject');
Route::get('/expenses/monthly-report', [ExpenseController::class, 'monthlyReport'])
    ->name('expenses.monthly-report');
// Custom logout route to override default
// Expense Management
Route::resource('expenses', ExpenseController::class);
Route::post('logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');