<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SupplierPayment extends Model
{
    use HasFactory;

    protected $fillable = [
        'supplier_id',
        'milk_supply_id',
        'payment_date',
        'amount',
        'payment_method',
        'reference_number',
        'payment_period_start',
        'payment_period_end',
        'notes',
        'status', // pending, approved, rejected
        'approved_by',
        'approved_at',
        'created_by',
    ];

    protected $casts = [
        'payment_date' => 'date',
        'amount' => 'decimal:2',
        'payment_period_start' => 'date',
        'payment_period_end' => 'date',
        'approved_at' => 'datetime',
    ];

    protected static function booted()
    {
        static::creating(function ($payment) {
            // If created_by is not set (auto-generated), use current user or system
            if (!$payment->created_by && auth()->check()) {
                $payment->created_by = auth()->id();
            }
            
            $payment->status = 'pending';
            
            // Auto-generate reference number if not provided
            if (!$payment->reference_number) {
                $payment->reference_number = 'PAY-' . strtoupper(uniqid());
            }
        });

        // When payment is approved, update related records if needed
        static::updated(function ($payment) {
            if ($payment->isDirty('status') && $payment->status === 'approved') {
                // You could update milk supply status here if needed
                // For example: mark milk supply as paid
            }
        });
    }

    // Relationships
    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }

    public function milkSupply()
    {
        return $this->belongsTo(MilkSupply::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function approver()
    {
        return $this->belongsTo(User::class, 'approved_by');
    }

    // Status checks
    public function isPending()
    {
        return $this->status === 'pending';
    }

    public function isApproved()
    {
        return $this->status === 'approved';
    }

    public function isRejected()
    {
        return $this->status === 'rejected';
    }

    // Scopes
    public function scopePending($query)
    {
        return $query->where('status', 'pending');
    }

    public function scopeApproved($query)
    {
        return $query->where('status', 'approved');
    }

    public function scopeRejected($query)
    {
        return $query->where('status', 'rejected');
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('notes', 'like', 'Auto-generated payment%');
    }

    public function scopeManual($query)
    {
        return $query->where('notes', 'not like', 'Auto-generated payment%');
    }
}